export const GET_WEATHER_EPIC = 'GET_WEATHER_EPIC';
export const GET_WEATHER_LOADING = 'GET_WEATHER_LOADING';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';
export const GET_WEATHER_CANCEL = 'GET_WEATHER_CANCEL';
