export const GET_COUNTRIES_EPIC = 'GET_COUNTRIES_EPIC';
export const GET_COUNTRIES_LOADING = 'GET_COUNTRIES_LOADING';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
export const GET_COUNTRIES_CANCEL = 'GET_COUNTRIES_CANCEL';

export const SELECT_COUNTRY = 'SELECT_COUNTRY';
